import apiClient from "./client";

export type MediaStatus = "pending" | "processing" | "completed" | "failed";
export type StepStatus = "pending" | "processing" | "success" | "failed";
export type MediaType = "image" | "video" | "avatar" | "audio";
export type MediaAssetType = "script" | "audio" | "image" | "caption" | "video" | "avatar";

export interface MediaStep {
    id: string;
    media_id: string;
    step: string;
    status: StepStatus;
    depends_on: string[] | null;
    blob_storage_id: string | string[] | null;
    retry_count: number;
    error_message: string | null;
    started_at: string | null;
    completed_at: string | null;
    created_at: string;
    updated_at: string;
}

export interface MediaAsset {
    id: string;
    media_id: string;
    type: MediaAssetType;
    blob_storage_id: string;
    metadata: Record<string, any> | null;
    created_at: string;
    url?: string; // Signed URL generated by frontend transformation or backend
}

export interface Media {
    id: string;
    type: MediaType;
    flow_key: string;
    status: MediaStatus;
    user_id: string | null;
    input_config: Record<string, any> | null;
    blob_storage_id: string | null;
    error_message: string | null;
    script: string | null;
    created_at: string;
    updated_at: string;
    completed_at: string | null;
    steps?: MediaStep[];
    assets?: MediaAsset[];
    // Legacy compatibility fields if needed during transition
    final_url?: string;
    assets_by_type?: Record<string, any[]>;
}

export interface CreateMediaDto {
    topic: string;
    type?: MediaType;
    flowKey?: string;
    language?: string;
    duration?: string;
    imageStyle?: string;
    imageAspectRatio?: string;
    voiceId?: string;
    imageProvider?: string;
}

export const mediaApi = {
    createMedia: async (data: CreateMediaDto): Promise<Media> => {
        const response = await apiClient.post("/media", data);
        return response.data;
    },

    getAllMedia: async (): Promise<Media[]> => {
        const response = await apiClient.get("/media/user/me");
        return response.data;
    },

    getMedia: async (id: string): Promise<Media> => {
        const response = await apiClient.get(`/media/${id}`);
        return response.data;
    },

    retryMedia: async (id: string): Promise<Media> => {
        const response = await apiClient.post(`/media/${id}/retry`);
        return response.data;
    },

    updateMedia: async (id: string, data: any): Promise<Media> => {
        const response = await apiClient.patch(`/media/${id}`, data);
        return response.data;
    },
};
